# This file provides instructions for packaging.

`Die-Hard`
	perl_version_from m`Die::Hard`;
	version_from      m`Die::Hard`;
	readme_from       m`Die::Hard`;
	requires          p`Moo`;
	test_requires     p`Test::Exception`;
	test_requires     p`Test::More 0.61`;
	.

